### ISSUE TITLE
bug: "kflex version" exits with error when no kubeconfig exists

### ISSUE THREAD

**Issue by namasl** [kubestellar/kubeflex#167]
### Describe the bug

When executing `kflex version` and no kubeconfig is defined, kflex will exit with error code 1, and error message `Error building kubeconfig: stat /home/nick/.kube/config: no such file or directory` (for user "nick" on Debian 12).

### Steps To Reproduce

Ensure that the `KUBECONFIG` environment variable is not set, and that `~/.kube/config` does not exist. Alternatively, set `KUBECONFIG` to a non-existant file.

### Expected Behavior

Print the version number (which currently does happen), and exit with no error regardless of the state of KUBECONFIG. There should be no need to look at KUBECONFIG.

**Comment by namasl** [comment]
I see now that the `version` sub-command subsequently tries to connect to a Kubernetes cluster to print its version too. Would it be better to print the error message to stderr but exit with a zero error code? If you just want to check the version of the `kflex` executable, it doesn't seem like that should exit with an error just because you haven't set up a cluster yet.

**Comment by pdettori** [comment]
@namasl thanks. Yes, behavior for `kflex version` should be modeled after `kubectl version`; for example:

```bash
KUBECONFIG=/tmp/foo kubectl version
W0112 17:16:51.739098   51309 loader.go:222] Config not found: /tmp/foo
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-04-14T13:21:19Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v5.0.1
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

**Comment by namasl** [comment]
OK, `kflex version` behavior is consistent with `kubectl version`. Closing
