### ISSUE TITLE
feature: less chatty progress indicator

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubeflex#173]
### Feature Description

When using KubeFlex in a GitHub workflow, the log is spammed with the progress spinners from KubeFlex.

### Proposed Solution

Do less chatty progress indicators.

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by MikeSpreitzer** [comment]
@pdettori

**Comment by pdettori** [comment]
@namasl  would you be interested in looking into a solution for this?

**Comment by pdettori** [comment]
We could have a flag that switches off the spinning wheel progress indicator when running in the CI/CD

**Comment by pdettori** [comment]
Addressed by #175
