### ISSUE TITLE
bug: "kflex init --create-kind" detects openshift cluster and installs there instead of in kind as instructed

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubeflex#186]
### Describe the bug

✔ Installing and patching nginx ingress...
✔ Kubeflex v0.4.1.fb99ff2 2024-01-25T04:26:23Z
✔ Ensuring kubeflex-system namespace...
✔ Checking if OpenShift cluster...
✔ OpenShift cluster detected
✔ Installing shared backend DB...
◐ Waiting for shared backend DB to become ready...

### Steps To Reproduce

1. oc login <openshift cluster>
2. kflex init --create-kind

✔ Installing and patching nginx ingress...
✔ Kubeflex v0.4.1.fb99ff2 2024-01-25T04:26:23Z
✔ Ensuring kubeflex-system namespace...
✔ Checking if OpenShift cluster...
✔ OpenShift cluster detected
✔ Installing shared backend DB...
◐ Waiting for shared backend DB to become ready...

### Expected Behavior

should not try to install on openshift cluster

**Comment by pdettori** [comment]
It looks like since `oc login` sets the `Kubeconfig` context to be the one of the OCP cluster, and then there is a check to find if it is an OCP cluster, it then does not create the kind cluster and uses OCP to install KubeFlex.

**Comment by pdettori** [comment]
Wondering what would be the right behavior. The idea is that if the user wants to install on OCP, he/she would have set the context to the one of the OCP cluster. But then the flag `--create-kind` should not be valid in that situation and an error should be returned. 

If the user intent is not to install on the OCP cluster but to create the kind cluster, it should start with a context that is not an OCP context.  User may switch to another context with `kubectl config use-context <other-context>` before running `kflex init`.

@clubanderson what would be your preference as user?

**Comment by clubanderson** [comment]
I would start by pointing out that --create-kind won't work if current context is set to openshift. Instruct user on how to switch context to use kind and re-run. User may not be sure how to get context from kind and should receive a simple example on how to do so.

**Comment by pdettori** [comment]
ok, so this could be mainly documentation. But we could also print an error message when the user use `kflex init` on an OCP context with `--create-kind` flag

**Comment by clubanderson** [comment]
yes - error with some ways to remit would be good way to go.
