### ISSUE TITLE
feature: Move CP and PCH CRDs out of `operator.yaml` into the special `chart/crds` folder

### ISSUE THREAD

**Issue by francostellari** [kubestellar/kubeflex#213]
### Feature Description

To ensure that CRDs are available to be sued by the chart, Helms makes user to install and wait for the avilability of the CRDs that are in the special folder `chart/crds`. This allows other components of the chart to install CRs.

Here is an example of error that may otherwise happen:

```
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: [resource mapping not found for name: "kubestellar" namespace: "" from "": no matches for kind "PostCreateHook" in version "tenancy.kflex.kubestellar.org/v1alpha1"
ensure CRDs are installed first, resource mapping not found for name: "ocm" namespace: "" from "": no matches for kind "PostCreateHook" in version "tenancy.kflex.kubestellar.org/v1alpha1"
ensure CRDs are installed first]
```

### Proposed Solution

Modify the `make chart` process to separate the CP and PCH CRDs into the special folder `chart/crds`

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by pdettori** [comment]
I have tried this approach and it did not work as expected. I ended up using a job to install the post create hooks - see https://github.com/kubestellar/kubeflex/blob/main/chart/templates/install-hooks.yaml . But if you find a better approach that uses the crds/ dir I am all for it.

**Comment by pdettori** [comment]
@francostellari: this issue should have been addressed in https://github.com/kubestellar/kubeflex/pull/231. Can we close this?

**Comment by francostellari** [comment]
completed
