### ISSUE TITLE
feature:  improve management of hosting cluster context

### ISSUE THREAD

**Issue by pdettori** [kubestellar/kubeflex#257]
### Feature Description

This feature should help with better managing the Hosting Context Preference set by kflex in the user's kubeconfig file, and help users with these two aspects 1) useful help message  2) new kflex command to set Hosting Context Preference 

### Proposed Solution

1) add new command `kflex set-hosting-ctx <some-existing-context>`
2) enhance the error message provided by #256 to guide the user to use such command when running into that "The initial (hosting) context is not known" state

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by pdettori** [comment]
cc: @MikeSpreitzer @francostellari @ezrasilvera

**Comment by MikeSpreitzer** [comment]
For 1 there is a simpler option: enhance the behavior of `kflex ctx` as suggested in point 1 of #255

**Comment by pdettori** [comment]
@MikeSpreitzer just to be clear, is you recommendation for 1 to set the hosting cluster preference in kubeconfig when doing `kflex init` rather then at the first `kflex create` ?

**Comment by MikeSpreitzer** [comment]
@pdettori: yes.

**Comment by pdettori** [comment]
This has been addressed in #266, #256 and #267
