### ISSUE TITLE
bug: Incomplete Pod for KubeFlex

### ISSUE THREAD

**Issue by milanahrae** [kubestellar/kubeflex#285]
### Describe the bug

I am trying to get everything set for Kubernetes but I am having trouble setting up KubeFlex. I need all 3 of my pods running to continue with downloding Kubeflex and 1/3 of my pods constantly says it's running and not completed. 

### Steps To Reproduce

![image (1)](https://github.com/user-attachments/assets/139e9e5d-eefd-444d-8821-2c4e37aec36f)
![image](https://github.com/user-attachments/assets/d44f7a5e-983a-4ebc-b9c7-d6cd55c9f4b6)
![Ngnix](https://github.com/user-attachments/assets/0dfb33b7-1722-4d1a-8467-f580e355f57a)

### Expected Behavior

My overall expected outcome is to create a Kubernetes cluster for Kubeflex and then continue the rest of the steps of the Getting Started guide on Kubestellar that requires Kubeflex. In order to do this, I need all 3 of my pods running for the Nginx Ingress Controller to be fully set up. I have tried accessing the ingress-nginx namespace to delete the pod and have a new one created, only for the same result to keep saying "running".

**Comment by pdettori** [comment]
Hi @milanahrae could you please provide more details on your environment - OS, memory, CPU, docker version, kind version? At first sight, it seems that there might not be enough resources in your system.

**Comment by milanahrae** [comment]
> Hi @milanahrae could you please provide more details on your environment - OS, memory, CPU, docker version, kind version? At first sight, it seems that there might not be enough resources in your system. 
![memory](https://github.com/user-attachments/assets/7c2f3a08-efdc-48f1-bc3d-9e57a66154ab)
![docker](https://github.com/user-attachments/assets/24c1ea09-6dcd-49ff-aa98-978bfcd26ebb)
This is what I have.

**Comment by pdettori** [comment]
@milanahrae seems like you may have enough resources, however, based on your screenshot above, it looks like the check_pre_req.sh fails for KubeFlex. Did you go over https://docs.kubestellar.io/release-0.24.0/direct/pre-reqs/ to install all pre-reqs? 

It is normal to see those 2 pods (`ingress-nginx-admission-create-rhh2c` and `ingress-nginx-admission-patch-jf42w`) as completed (these are created by 2 jobs - `ingress-nginx-admission-create` and `ingress-nginx-admission-patch`). As for the 3rd one, that should stay in `running` state as that is a controller, and controllers in Kubernetes are long-running.  It may take some time (up to 120 s) for that pod to get to 'READY' (the row for `ingress-nginx-controller-xxx-xxx` should show 1/1 for the READY column) - does it ever gets to that state ? 

If not, could you please show the logs for that controller pod (if you restarted the install, that name may have changed)

```
kubectl logs -n ingress-nginx ingress-nginx-controller-dcf8d6f6d-4p4fb 
```

**Comment by pdettori** [comment]
@milanahrae : you are welcome. Closing the issue.
