### ISSUE TITLE
feature: Need more forceful kflex commands

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubeflex#288]
### Feature Description

(A) `kflex ctx $something` will do nothing if there is already a kubeconfig context named `$something` --- even if that context is a broken old thing rather than what this command would create if that context did not exist. There should be something like `fklex ctx --force $something` that will replace the context even if it already exists.

(B) `kflex ctx` will not replace it if the kubeconfig extension naming the hosting cluster context exists but holds a bad value (the name of a context that exists but is no longer the right context). There should be something like `kflex ctx use-current-for-hosting` that sets the extension contents unconditionally.

### Proposed Solution

See above.

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by pdettori** [comment]
@MikeSpreitzer are you suggesting to have both `klex ctx --force $something` and `kflex ctx use-current-for-hosting` or just one of the two would be sufficient ?

**Comment by MikeSpreitzer** [comment]
Both. They address different needs.
