### ISSUE TITLE
bug: Forbidden 403 on helm upgrade

### ISSUE THREAD

**Issue by milanahrae** [kubestellar/kubeflex#295]
### Describe the bug

![image (1)](https://github.com/user-attachments/assets/8b8cf1c3-609a-4c26-85ad-74e7391bd0c2)

### Steps To Reproduce

Forbidden 403 on helm upgrade during getting started install.

### Expected Behavior

Use Core Helm chart to initialize KubeFlex and create ITS and WDS[#](https://docs.kubestellar.io/release-0.24.0/direct/get-started/#use-core-helm-chart-to-initialize-kubeflex-and-create-its-and-wds)

helm upgrade --install ks-core oci://ghcr.io/kubestellar/kubestellar/core-chart \
    --version $KUBESTELLAR_VERSION \
    --set-json='ITSes=[{"name":"its1"}]' \
    --set-json='WDSes=[{"name":"wds1"}]'
That command will print some notes about how to get kubeconfig "contexts" named "its1" and "wds1" defined. Do that, because those contexts are used in the following.

**Comment by MikeSpreitzer** [comment]
This is not at all a KubeFlex problem. The problem concerns fetching the KubeStellar core Helm chart prior to anything about KubeFlex. I will create an Issue in the kubestellar repository for this.

**Comment by MikeSpreitzer** [comment]
See https://github.com/kubestellar/kubestellar/issues/2544 instead.
